---
# Rol openshot — OpenShot Video Editor via Chocolatey.
- name: Instalar OpenShot {{ openshot_version | default('(ultima)', true) }}
  chocolatey.chocolatey.win_chocolatey:
    name: openshot
    version: "{{ openshot_version | default(omit, true) }}"
    state: present
