- name: Comprobar si el host local está en known_hosts
  shell: ssh-keygen -F $(hostname) || ssh-keygen -F localhost
  register: known_host_check
  ignore_errors: true
  changed_when: false
  when: not ssh_key.stat.exists

- name: Conectar SSH a sí mismo para añadir la clave a known_hosts
  shell: ssh -o StrictHostKeyChecking=accept-new -o BatchMode=yes localhost "exit 0" || ssh -o StrictHostKeyChecking=accept-new -o BatchMode=yes $(hostname) "exit 0"
  when: 
    - not ssh_key.stat.exists 
    - known_host_check.rc != 0

