---

# Para ejecutar este playbook:     ip pruebas 10.0.72.
#    ansible-playbook -i ../equipos.ini roles.yaml --ssh-extra-args="-o StrictHostKeyChecking=no"
- hosts: all
  become: yes
  roles:
     - vmware
#     - certificados
#     - obs
#     - xrdp
#     - vscode     

    
#   vars:
#     obs_version: "30.0.2"  # versión deseada, personalizable desde el playbook o línea de comandos
  
