---

# Para ejecutar este playbook:     ip pruebas 10.0.72.
#    ansible-playbook -i ../equipos.ini roles.yaml --ssh-extra-args="-o StrictHostKeyChecking=no"
#    ansible-playbook -i localhost, --connection=local roles.yaml --ssh-extra-args="-o StrictHostKeyChecking=no"
- hosts: all
  become: yes

  pre_tasks:
    - name: Actualizar cache apt 
      apt:
        update_cache: yes
  roles:
     - comparteaula  # en -00 crear una carpeta compartida en /home/Comparte, y en el resto montar esa carpeta compartida en /Comparte
    # nvidia: falta que separar en caso de no haber tarjeta nvidia. Ahora mismo detiene todo el playbook si no pongo el ignore_errors 
    #  - role: nvidia
    #  - role: certificados
    #  - role: obs
    #  - role: xrdp
    #  - role: vscode
    #  - role: virtualbox #Roles para virtualbox: virtualbox  (instal)  ; virtualboxFUERA (desinstala virtualbox y sus repositorios)
    #                     #PORHACER: virtualbox no me instalar exactamente la versión que le digo, sino la última disponible 
    #  #vmware : falta dejar bundle en un sitio accesible para que funcione desde el LiveCD
    #  - role: vmware
    
  

#POR HACER:
#      - basicos      #cosas que debieras estar desde el livecd pero que recomprobamos #[python, ansible, pip, pipx] 

#      - contenedores  #[docker y podman]
#      - hashicorp     #[terraform, packer, vagrant]
#      - predominio    #ficheros necesarios para unir el equipo al dominio  
#      - clienteOnedrive
#      - ¿anaconda? ¿dbeaver?#   






#   vars:
#     obs_version: "30.0.2"  # versión deseada, personalizable desde el playbook o línea de comandos
  
