---

# Para ejecutar este playbook:     ip pruebas 10.0.72.
#    ansible-playbook -i ../equipos.ini roles.yaml --ssh-extra-args="-o StrictHostKeyChecking=no"
- hosts: all
  become: yes

  pre_tasks:
    - name: Actualizar cache apt 
      apt:
        update_cache: yes
  roles:
     - nvidia
     - certificados
     - obs
     - xrdp
     - vscode     
     - vmware
    #Roles para virtualbox: virtualbox  (instal)  ; virtualboxFUERA (desinstala virtualbox y sus repositorios)
     - virtualbox
#PORHACER: virtualbox no me instalar exactamente la versión que le digo, sino la última disponible 
     

#POR HACER:
#      - python  #[python, ansible, pip, pipx] 
#      - contenedores  #[docker y podman]
#      - hashicorp     #[terraform, packer, vagrant]
#      - ¿anaconda? ¿dbeaver?
#      - virtualbox    #[virtualbox, vagrant] 





#   vars:
#     obs_version: "30.0.2"  # versión deseada, personalizable desde el playbook o línea de comandos
  
