---

# Para ejecutar este playbook:     ip pruebas 10.0.72.
#    ansible-playbook -i ../equipos.ini roles.yaml --ssh-extra-args="-o StrictHostKeyChecking=no"
#    ansible-playbook -i localhost, --connection=local roles.yaml --ssh-extra-args="-o StrictHostKeyChecking=no"
- hosts: all
  become: yes

  pre_tasks:
    - name: Actualizar cache apt 
      apt:
        update_cache: yes
  roles:
    # nvidia: falta que separar en caso de no haber tarjeta nvidia. Ahora mismo detiene todo el playbook si no pongo el ignore_errors 
    # - role: nvidia
    #   ignore_errors: yes
     - role: certificados
     - role: obs
     - role: xrdp
     - role: vscode
    #Roles para virtualbox: virtualbox  (instal)  ; virtualboxFUERA (desinstala virtualbox y sus repositorios)
     - role: virtualbox
     #vmware : falta dejar bundle en un sitio accesible 
     - role: vmware
       ignore_errors: yes
    
     
#PORHACER: virtualbox no me instalar exactamente la versión que le digo, sino la última disponible 
     

#POR HACER:
#      - python  #[python, ansible, pip, pipx] 
#      - contenedores  #[docker y podman]
#      - hashicorp     #[terraform, packer, vagrant]
#      - ¿anaconda? ¿dbeaver?
#      - virtualbox    #[virtualbox, vagrant] 





#   vars:
#     obs_version: "30.0.2"  # versión deseada, personalizable desde el playbook o línea de comandos
  
