---

# Para ejecutar este playbook:
#    ansible-playbook -i ../equipos.ini roles.yaml --ssh-extra-args="-o StrictHostKeyChecking=no"
- hosts: all
  become: yes
  roles:
    - obs
    - xrdp
    - vscode     #COMPROBAR QUE NO JOROBA EL RESTO DE INSTALACIONES! 
    - certificados
    
#   vars:
#     obs_version: "30.0.2"  # versión deseada, personalizable desde el playbook o línea de comandos
  
