---

# Para ejecutar este playbook:     (en la carpeta donde se encuentra)
#    ansible all -i ../equiposCIABD.ini -m ping
#    ansible-playbook -i ../equiposCEIABD.ini roles.yaml --ssh-extra-args="-o StrictHostKeyChecking=no"
#    ansible-playbook -i localhost, --connection=local roles.yaml --ssh-extra-args="-o StrictHostKeyChecking=no"

- hosts: all
  become: yes

  pre_tasks:
    - name: Actualizar cache apt (para no hacerlo en cada rol)
      apt:
        update_cache: yes
  roles:
     - basicos       #cosas que debieras estar desde el livecd pero que recomprobamos #[python, pip, pipx, ansible] 
     - comparteaula  # en -00 crear una carpeta compartida en /home/Comparte, y en el resto montar esa carpeta compartida en /Comparte
    # nvidia: falta que separar en caso de no haber tarjeta nvidia. Ahora mismo detiene todo el playbook si no pongo el ignore_errors 
     - nvidia
     - certificados
     - obs
     - xrdp
     - vscode
     - virtualbox #Roles para virtualbox: virtualbox  (instal)  ; virtualboxFUERA (desinstala virtualbox y sus repositorios)
    #             #TODO: virtualbox no me instalar exactamente la versión que le digo, sino la última disponible 
     - vmware  #TODO: pide compilar (como sudo) en el primer arranque. Hay que evitarlo.
     #- contenedores  #[docker y podman  (+sus compose)]    #por hacer
  

#POR HACER:
#      - hashicorp     #[terraform, packer, vagrant]
#      - predominio    #ficheros necesarios para unir el equipo al dominio  
#      - clienteOnedrive
#      - ¿anaconda? ¿dbeaver?#   






#   vars:
#     obs_version: "30.0.2"  # versión deseada, personalizable desde el playbook o línea de comandos
  
